---
layout: default
---

# 👋 Hi, I'm Jared Barbero

Welcome to my portfolio website. Below are some of the projects I've worked on:

## 💻 Web Development
- [Portfolio Site](https://github.com/yourusername/portfolio-site) – A personal portfolio.
- [Blog CMS](https://github.com/yourusername/blog-cms) – A custom blog platform.

## 📊 Data Projects
- [YouTube Data Analysis]https://github.com/jaredpbarbero/Youtuber_Analysis) – Analysis of YouTube channel data using SQL and Python.

## 📬 Contact
Want to get in touch? [Email me](mailto:jrdbarbero@gmail.com) or connect on [LinkedIn](www.linkedin.com/in/jared-barbero-3590091a3).
